
package com.contact.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactPersistServiceImpl", targetNamespace = "http://serviceimpl.contact.com/", wsdlLocation = "http://localhost:8989/ws/contactservice?wsdl")
public class ContactPersistServiceImpl
    extends Service
{

    private final static URL CONTACTPERSISTSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException CONTACTPERSISTSERVICEIMPL_EXCEPTION;
    private final static QName CONTACTPERSISTSERVICEIMPL_QNAME = new QName("http://serviceimpl.contact.com/", "ContactPersistServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/ws/contactservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTPERSISTSERVICEIMPL_WSDL_LOCATION = url;
        CONTACTPERSISTSERVICEIMPL_EXCEPTION = e;
    }

    public ContactPersistServiceImpl() {
        super(__getWsdlLocation(), CONTACTPERSISTSERVICEIMPL_QNAME);
    }

    public ContactPersistServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTPERSISTSERVICEIMPL_QNAME, features);
    }

    public ContactPersistServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, CONTACTPERSISTSERVICEIMPL_QNAME);
    }

    public ContactPersistServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTPERSISTSERVICEIMPL_QNAME, features);
    }

    public ContactPersistServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactPersistServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactService
     */
    @WebEndpoint(name = "ContactPersistPort")
    public ContactService getContactPersistPort() {
        return super.getPort(new QName("http://serviceimpl.contact.com/", "ContactPersistPort"), ContactService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactService
     */
    @WebEndpoint(name = "ContactPersistPort")
    public ContactService getContactPersistPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.contact.com/", "ContactPersistPort"), ContactService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTPERSISTSERVICEIMPL_EXCEPTION!= null) {
            throw CONTACTPERSISTSERVICEIMPL_EXCEPTION;
        }
        return CONTACTPERSISTSERVICEIMPL_WSDL_LOCATION;
    }

}
